# Generated by Django 5.0.2 on 2024-02-26 09:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Information',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ram_usage', models.CharField(max_length=200, verbose_name='램 사용량')),
            ],
        ),
        migrations.CreateModel(
            name='ScreenShot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='', verbose_name='이미지 파일')),
                ('uploaded_date', models.DateTimeField(auto_now_add=True)),
                ('context', models.TextField(verbose_name='본문')),
            ],
        ),
        migrations.CreateModel(
            name='Computer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('computer_name', models.CharField(max_length=50, verbose_name='컴퓨터 이름')),
                ('information', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='control_panel.information')),
                ('screenshots', models.ManyToManyField(to='control_panel.screenshot')),
            ],
        ),
    ]
